export const ADD_DISH = "ADD_DISH";
export const DISH_ERROR = "DISH_ERROR";
export const SUCCESS_FALSE = "SUCCESS_FALSE";
export const GET_DISHES = "GET_DISHES";
export const GET_INGREDIENTS = "GET_INGREDIENTS";
export const INGREDIENT_ERROR = "INGREDIENT_ERROR";
export const ADD_INGREDIENT = "ADD_INGREDIENT";